services:
  web:
    build: .
    ports:
      - "${FASTAPI_PORT}:5000"
    depends_on:
      - postgres
      
  postgres:
    image: "postgres:alpine3.18"
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql