services:
  auth_service:
    env_file:
      - .env
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - postgres_auth

  postgres_auth:
    image: "postgres:alpine3.18"
    env_file:
      - .env
    container_name: postgres_database
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: "bitnami/minio:latest"
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
